/**
 * Teks mode suara panel asisten (id/en). `{name}` = nama asisten,
 * `{waktu}` = sisa waktu (m:ss), `{durasi}` = durasi tunggu kuota.
 */

export interface AssistantVoiceText {
	start: string;
	stop: string;
	status: {
		connecting: string;
		ready: string;
		listening: string;
		answering: string;
	};
	micActive: string;
	muteAnswer: string;
	unmuteAnswer: string;
	muteMic: string;
	unmuteMic: string;
	remaining: string;
	extendInvite: string;
	extend: string;
	voiceMarker: string;
	dismiss: string;
	unsupported: string;
	/** Dibacakan GPT-Live saat ucapan tak terbaca / jawaban gagal diambil. */
	commentary: {
		empty: string;
		failed: string;
	};
	consent: {
		title: string;
		body: string;
		accept: string;
		decline: string;
	};
	ended: {
		idle: string;
		maxDuration: string;
		quota: string;
		closed: string;
	};
	errors: {
		micDenied: string;
		quota: string;
		slotEmpty: string;
		connectionLost: string;
		secondTab: string;
		forbidden: string;
		failed: string;
	};
}

const id: AssistantVoiceText = {
	start: "Mulai bicara dengan {name}",
	stop: "Matikan mode suara",
	status: {
		connecting: "Menghubungkan…",
		ready: "Siap bicara",
		listening: "Mendengarkan…",
		answering: "Menjawab…",
	},
	micActive: "Mikrofon aktif",
	muteAnswer: "Bisukan suara jawaban",
	unmuteAnswer: "Bunyikan suara jawaban",
	muteMic: "Matikan mikrofon",
	unmuteMic: "Nyalakan mikrofon",
	remaining: "Sisa {waktu}",
	extendInvite: "Sesi suara hampir habis. Perpanjang 1 menit?",
	extend: "Perpanjang",
	voiceMarker: "Pesan suara",
	dismiss: "Tutup pesan",
	unsupported: "Mode suara hanya tersedia di Chrome atau Edge versi desktop.",
	commentary: {
		empty: "Ucapan tidak terbaca. Mohon ulangi.",
		failed: "Maaf, jawabannya gagal diambil. Silakan tanyakan lagi.",
	},
	consent: {
		title: "Izinkan mode suara",
		body: "Selama mode suara aktif, mikrofon Anda menyala dan suara Anda dikirim ke OpenAI untuk diproses. Suara jawaban {name} dibuat oleh AI. Rekaman suara tidak disimpan.",
		accept: "Setuju dan mulai",
		decline: "Batal",
	},
	ended: {
		idle: "Mode suara dimatikan karena tidak ada percakapan.",
		maxDuration: "Batas waktu sesi suara tercapai.",
		quota: "Jatah menit suara hari ini sudah habis.",
		closed: "Sesi suara berakhir.",
	},
	errors: {
		micDenied:
			"Akses mikrofon ditolak. Izinkan mikrofon di pengaturan browser lalu coba lagi.",
		quota: "Jatah menit suara hari ini sudah habis. Coba lagi dalam {durasi}.",
		slotEmpty: "Mode suara belum disiapkan admin.",
		connectionLost: "Koneksi suara terputus. Silakan mulai lagi.",
		secondTab:
			"Mode suara sedang aktif di tab atau perangkat lain. Matikan di sana dulu.",
		forbidden: "Akun Anda tidak diizinkan memakai mode suara.",
		failed: "Mode suara gagal dimulai. Coba lagi sebentar.",
	},
};

const en: AssistantVoiceText = {
	start: "Start talking with {name}",
	stop: "Turn off voice mode",
	status: {
		connecting: "Connecting…",
		ready: "Ready to talk",
		listening: "Listening…",
		answering: "Answering…",
	},
	micActive: "Microphone on",
	muteAnswer: "Mute answer voice",
	unmuteAnswer: "Unmute answer voice",
	muteMic: "Mute microphone",
	unmuteMic: "Unmute microphone",
	remaining: "{waktu} left",
	extendInvite: "Voice session is almost over. Extend by 1 minute?",
	extend: "Extend",
	voiceMarker: "Voice message",
	dismiss: "Dismiss message",
	unsupported: "Voice mode is only available in desktop Chrome or Edge.",
	commentary: {
		empty: "I couldn't make out what you said. Please repeat.",
		failed: "Sorry, I couldn't get the answer. Please ask again.",
	},
	consent: {
		title: "Allow voice mode",
		body: "While voice mode is on, your microphone is active and your voice is sent to OpenAI for processing. {name}'s answer voice is generated by AI. Audio is not stored.",
		accept: "Agree and start",
		decline: "Cancel",
	},
	ended: {
		idle: "Voice mode turned off because nobody was talking.",
		maxDuration: "The voice session time limit was reached.",
		quota: "Today's voice minutes are used up.",
		closed: "The voice session has ended.",
	},
	errors: {
		micDenied:
			"Microphone access was denied. Allow the microphone in your browser settings and try again.",
		quota: "Today's voice minutes are used up. Try again in {durasi}.",
		slotEmpty: "Voice mode has not been set up by an admin.",
		connectionLost: "The voice connection was lost. Please start again.",
		secondTab:
			"Voice mode is already active in another tab or device. Turn it off there first.",
		forbidden: "Your account is not allowed to use voice mode.",
		failed: "Voice mode failed to start. Please try again shortly.",
	},
};

export const assistantVoiceTexts = { id, en } as const;
