/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UsersIdRouteImport } from './routes/users/$id'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as DashboardSosialRouteImport } from './routes/dashboard/sosial'
import { Route as DashboardPengaturanRouteImport } from './routes/dashboard/pengaturan'
import { Route as DashboardPengaduanLayananPublikRouteImport } from './routes/dashboard/pengaduan-layanan-publik'
import { Route as DashboardKinerjaDivisiRouteImport } from './routes/dashboard/kinerja-divisi'
import { Route as DashboardKeuanganAnggaranRouteImport } from './routes/dashboard/keuangan-anggaran'
import { Route as DashboardKeamananRouteImport } from './routes/dashboard/keamanan'
import { Route as DashboardJennaAnalyticRouteImport } from './routes/dashboard/jenna-analytic'
import { Route as DashboardDemografiPekerjaanRouteImport } from './routes/dashboard/demografi-pekerjaan'
import { Route as DashboardBumdesRouteImport } from './routes/dashboard/bumdes'
import { Route as DashboardBantuanRouteImport } from './routes/dashboard/bantuan'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminApikeyRouteImport } from './routes/admin/apikey'
import { Route as DashboardPengaturanUmumRouteRouteImport } from './routes/dashboard/pengaturan/umum.route'
import { Route as DashboardPengaturanNotifikasiRouteRouteImport } from './routes/dashboard/pengaturan/notifikasi.route'
import { Route as DashboardPengaturanKeamananRouteRouteImport } from './routes/dashboard/pengaturan/keamanan.route'
import { Route as DashboardPengaturanAksesDanTimRouteRouteImport } from './routes/dashboard/pengaturan/akses-dan-tim.route'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSosialRoute = DashboardSosialRouteImport.update({
  id: '/sosial',
  path: '/sosial',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPengaturanRoute = DashboardPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPengaduanLayananPublikRoute =
  DashboardPengaduanLayananPublikRouteImport.update({
    id: '/pengaduan-layanan-publik',
    path: '/pengaduan-layanan-publik',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardKinerjaDivisiRoute = DashboardKinerjaDivisiRouteImport.update({
  id: '/kinerja-divisi',
  path: '/kinerja-divisi',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardKeuanganAnggaranRoute =
  DashboardKeuanganAnggaranRouteImport.update({
    id: '/keuangan-anggaran',
    path: '/keuangan-anggaran',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardKeamananRoute = DashboardKeamananRouteImport.update({
  id: '/keamanan',
  path: '/keamanan',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJennaAnalyticRoute = DashboardJennaAnalyticRouteImport.update({
  id: '/jenna-analytic',
  path: '/jenna-analytic',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDemografiPekerjaanRoute =
  DashboardDemografiPekerjaanRouteImport.update({
    id: '/demografi-pekerjaan',
    path: '/demografi-pekerjaan',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardBumdesRoute = DashboardBumdesRouteImport.update({
  id: '/bumdes',
  path: '/bumdes',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBantuanRoute = DashboardBantuanRouteImport.update({
  id: '/bantuan',
  path: '/bantuan',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApikeyRoute = AdminApikeyRouteImport.update({
  id: '/apikey',
  path: '/apikey',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DashboardPengaturanUmumRouteRoute =
  DashboardPengaturanUmumRouteRouteImport.update({
    id: '/umum',
    path: '/umum',
    getParentRoute: () => DashboardPengaturanRoute,
  } as any)
const DashboardPengaturanNotifikasiRouteRoute =
  DashboardPengaturanNotifikasiRouteRouteImport.update({
    id: '/notifikasi',
    path: '/notifikasi',
    getParentRoute: () => DashboardPengaturanRoute,
  } as any)
const DashboardPengaturanKeamananRouteRoute =
  DashboardPengaturanKeamananRouteRouteImport.update({
    id: '/keamanan',
    path: '/keamanan',
    getParentRoute: () => DashboardPengaturanRoute,
  } as any)
const DashboardPengaturanAksesDanTimRouteRoute =
  DashboardPengaturanAksesDanTimRouteRouteImport.update({
    id: '/akses-dan-tim',
    path: '/akses-dan-tim',
    getParentRoute: () => DashboardPengaturanRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/apikey': typeof AdminApikeyRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/bantuan': typeof DashboardBantuanRoute
  '/dashboard/bumdes': typeof DashboardBumdesRoute
  '/dashboard/demografi-pekerjaan': typeof DashboardDemografiPekerjaanRoute
  '/dashboard/jenna-analytic': typeof DashboardJennaAnalyticRoute
  '/dashboard/keamanan': typeof DashboardKeamananRoute
  '/dashboard/keuangan-anggaran': typeof DashboardKeuanganAnggaranRoute
  '/dashboard/kinerja-divisi': typeof DashboardKinerjaDivisiRoute
  '/dashboard/pengaduan-layanan-publik': typeof DashboardPengaduanLayananPublikRoute
  '/dashboard/pengaturan': typeof DashboardPengaturanRouteWithChildren
  '/dashboard/sosial': typeof DashboardSosialRoute
  '/profile/edit': typeof ProfileEditRoute
  '/users/$id': typeof UsersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/users/': typeof UsersIndexRoute
  '/dashboard/pengaturan/akses-dan-tim': typeof DashboardPengaturanAksesDanTimRouteRoute
  '/dashboard/pengaturan/keamanan': typeof DashboardPengaturanKeamananRouteRoute
  '/dashboard/pengaturan/notifikasi': typeof DashboardPengaturanNotifikasiRouteRoute
  '/dashboard/pengaturan/umum': typeof DashboardPengaturanUmumRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/apikey': typeof AdminApikeyRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/bantuan': typeof DashboardBantuanRoute
  '/dashboard/bumdes': typeof DashboardBumdesRoute
  '/dashboard/demografi-pekerjaan': typeof DashboardDemografiPekerjaanRoute
  '/dashboard/jenna-analytic': typeof DashboardJennaAnalyticRoute
  '/dashboard/keamanan': typeof DashboardKeamananRoute
  '/dashboard/keuangan-anggaran': typeof DashboardKeuanganAnggaranRoute
  '/dashboard/kinerja-divisi': typeof DashboardKinerjaDivisiRoute
  '/dashboard/pengaduan-layanan-publik': typeof DashboardPengaduanLayananPublikRoute
  '/dashboard/pengaturan': typeof DashboardPengaturanRouteWithChildren
  '/dashboard/sosial': typeof DashboardSosialRoute
  '/profile/edit': typeof ProfileEditRoute
  '/users/$id': typeof UsersIdRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/users': typeof UsersIndexRoute
  '/dashboard/pengaturan/akses-dan-tim': typeof DashboardPengaturanAksesDanTimRouteRoute
  '/dashboard/pengaturan/keamanan': typeof DashboardPengaturanKeamananRouteRoute
  '/dashboard/pengaturan/notifikasi': typeof DashboardPengaturanNotifikasiRouteRoute
  '/dashboard/pengaturan/umum': typeof DashboardPengaturanUmumRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/apikey': typeof AdminApikeyRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/bantuan': typeof DashboardBantuanRoute
  '/dashboard/bumdes': typeof DashboardBumdesRoute
  '/dashboard/demografi-pekerjaan': typeof DashboardDemografiPekerjaanRoute
  '/dashboard/jenna-analytic': typeof DashboardJennaAnalyticRoute
  '/dashboard/keamanan': typeof DashboardKeamananRoute
  '/dashboard/keuangan-anggaran': typeof DashboardKeuanganAnggaranRoute
  '/dashboard/kinerja-divisi': typeof DashboardKinerjaDivisiRoute
  '/dashboard/pengaduan-layanan-publik': typeof DashboardPengaduanLayananPublikRoute
  '/dashboard/pengaturan': typeof DashboardPengaturanRouteWithChildren
  '/dashboard/sosial': typeof DashboardSosialRoute
  '/profile/edit': typeof ProfileEditRoute
  '/users/$id': typeof UsersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/users/': typeof UsersIndexRoute
  '/dashboard/pengaturan/akses-dan-tim': typeof DashboardPengaturanAksesDanTimRouteRoute
  '/dashboard/pengaturan/keamanan': typeof DashboardPengaturanKeamananRouteRoute
  '/dashboard/pengaturan/notifikasi': typeof DashboardPengaturanNotifikasiRouteRoute
  '/dashboard/pengaturan/umum': typeof DashboardPengaturanUmumRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/admin/apikey'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/bantuan'
    | '/dashboard/bumdes'
    | '/dashboard/demografi-pekerjaan'
    | '/dashboard/jenna-analytic'
    | '/dashboard/keamanan'
    | '/dashboard/keuangan-anggaran'
    | '/dashboard/kinerja-divisi'
    | '/dashboard/pengaduan-layanan-publik'
    | '/dashboard/pengaturan'
    | '/dashboard/sosial'
    | '/profile/edit'
    | '/users/$id'
    | '/admin/'
    | '/dashboard/'
    | '/profile/'
    | '/users/'
    | '/dashboard/pengaturan/akses-dan-tim'
    | '/dashboard/pengaturan/keamanan'
    | '/dashboard/pengaturan/notifikasi'
    | '/dashboard/pengaturan/umum'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/admin/apikey'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/bantuan'
    | '/dashboard/bumdes'
    | '/dashboard/demografi-pekerjaan'
    | '/dashboard/jenna-analytic'
    | '/dashboard/keamanan'
    | '/dashboard/keuangan-anggaran'
    | '/dashboard/kinerja-divisi'
    | '/dashboard/pengaduan-layanan-publik'
    | '/dashboard/pengaturan'
    | '/dashboard/sosial'
    | '/profile/edit'
    | '/users/$id'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/users'
    | '/dashboard/pengaturan/akses-dan-tim'
    | '/dashboard/pengaturan/keamanan'
    | '/dashboard/pengaturan/notifikasi'
    | '/dashboard/pengaturan/umum'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/admin/apikey'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/bantuan'
    | '/dashboard/bumdes'
    | '/dashboard/demografi-pekerjaan'
    | '/dashboard/jenna-analytic'
    | '/dashboard/keamanan'
    | '/dashboard/keuangan-anggaran'
    | '/dashboard/kinerja-divisi'
    | '/dashboard/pengaduan-layanan-publik'
    | '/dashboard/pengaturan'
    | '/dashboard/sosial'
    | '/profile/edit'
    | '/users/$id'
    | '/admin/'
    | '/dashboard/'
    | '/profile/'
    | '/users/'
    | '/dashboard/pengaturan/akses-dan-tim'
    | '/dashboard/pengaturan/keamanan'
    | '/dashboard/pengaturan/notifikasi'
    | '/dashboard/pengaturan/umum'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ProfileEditRoute: typeof ProfileEditRoute
  UsersIdRoute: typeof UsersIdRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sosial': {
      id: '/dashboard/sosial'
      path: '/sosial'
      fullPath: '/dashboard/sosial'
      preLoaderRoute: typeof DashboardSosialRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/pengaturan': {
      id: '/dashboard/pengaturan'
      path: '/pengaturan'
      fullPath: '/dashboard/pengaturan'
      preLoaderRoute: typeof DashboardPengaturanRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/pengaduan-layanan-publik': {
      id: '/dashboard/pengaduan-layanan-publik'
      path: '/pengaduan-layanan-publik'
      fullPath: '/dashboard/pengaduan-layanan-publik'
      preLoaderRoute: typeof DashboardPengaduanLayananPublikRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/kinerja-divisi': {
      id: '/dashboard/kinerja-divisi'
      path: '/kinerja-divisi'
      fullPath: '/dashboard/kinerja-divisi'
      preLoaderRoute: typeof DashboardKinerjaDivisiRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/keuangan-anggaran': {
      id: '/dashboard/keuangan-anggaran'
      path: '/keuangan-anggaran'
      fullPath: '/dashboard/keuangan-anggaran'
      preLoaderRoute: typeof DashboardKeuanganAnggaranRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/keamanan': {
      id: '/dashboard/keamanan'
      path: '/keamanan'
      fullPath: '/dashboard/keamanan'
      preLoaderRoute: typeof DashboardKeamananRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/jenna-analytic': {
      id: '/dashboard/jenna-analytic'
      path: '/jenna-analytic'
      fullPath: '/dashboard/jenna-analytic'
      preLoaderRoute: typeof DashboardJennaAnalyticRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/demografi-pekerjaan': {
      id: '/dashboard/demografi-pekerjaan'
      path: '/demografi-pekerjaan'
      fullPath: '/dashboard/demografi-pekerjaan'
      preLoaderRoute: typeof DashboardDemografiPekerjaanRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/bumdes': {
      id: '/dashboard/bumdes'
      path: '/bumdes'
      fullPath: '/dashboard/bumdes'
      preLoaderRoute: typeof DashboardBumdesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/bantuan': {
      id: '/dashboard/bantuan'
      path: '/bantuan'
      fullPath: '/dashboard/bantuan'
      preLoaderRoute: typeof DashboardBantuanRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/apikey': {
      id: '/admin/apikey'
      path: '/apikey'
      fullPath: '/admin/apikey'
      preLoaderRoute: typeof AdminApikeyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/dashboard/pengaturan/umum': {
      id: '/dashboard/pengaturan/umum'
      path: '/umum'
      fullPath: '/dashboard/pengaturan/umum'
      preLoaderRoute: typeof DashboardPengaturanUmumRouteRouteImport
      parentRoute: typeof DashboardPengaturanRoute
    }
    '/dashboard/pengaturan/notifikasi': {
      id: '/dashboard/pengaturan/notifikasi'
      path: '/notifikasi'
      fullPath: '/dashboard/pengaturan/notifikasi'
      preLoaderRoute: typeof DashboardPengaturanNotifikasiRouteRouteImport
      parentRoute: typeof DashboardPengaturanRoute
    }
    '/dashboard/pengaturan/keamanan': {
      id: '/dashboard/pengaturan/keamanan'
      path: '/keamanan'
      fullPath: '/dashboard/pengaturan/keamanan'
      preLoaderRoute: typeof DashboardPengaturanKeamananRouteRouteImport
      parentRoute: typeof DashboardPengaturanRoute
    }
    '/dashboard/pengaturan/akses-dan-tim': {
      id: '/dashboard/pengaturan/akses-dan-tim'
      path: '/akses-dan-tim'
      fullPath: '/dashboard/pengaturan/akses-dan-tim'
      preLoaderRoute: typeof DashboardPengaturanAksesDanTimRouteRouteImport
      parentRoute: typeof DashboardPengaturanRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminApikeyRoute: typeof AdminApikeyRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminApikeyRoute: AdminApikeyRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DashboardPengaturanRouteChildren {
  DashboardPengaturanAksesDanTimRouteRoute: typeof DashboardPengaturanAksesDanTimRouteRoute
  DashboardPengaturanKeamananRouteRoute: typeof DashboardPengaturanKeamananRouteRoute
  DashboardPengaturanNotifikasiRouteRoute: typeof DashboardPengaturanNotifikasiRouteRoute
  DashboardPengaturanUmumRouteRoute: typeof DashboardPengaturanUmumRouteRoute
}

const DashboardPengaturanRouteChildren: DashboardPengaturanRouteChildren = {
  DashboardPengaturanAksesDanTimRouteRoute:
    DashboardPengaturanAksesDanTimRouteRoute,
  DashboardPengaturanKeamananRouteRoute: DashboardPengaturanKeamananRouteRoute,
  DashboardPengaturanNotifikasiRouteRoute:
    DashboardPengaturanNotifikasiRouteRoute,
  DashboardPengaturanUmumRouteRoute: DashboardPengaturanUmumRouteRoute,
}

const DashboardPengaturanRouteWithChildren =
  DashboardPengaturanRoute._addFileChildren(DashboardPengaturanRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardBantuanRoute: typeof DashboardBantuanRoute
  DashboardBumdesRoute: typeof DashboardBumdesRoute
  DashboardDemografiPekerjaanRoute: typeof DashboardDemografiPekerjaanRoute
  DashboardJennaAnalyticRoute: typeof DashboardJennaAnalyticRoute
  DashboardKeamananRoute: typeof DashboardKeamananRoute
  DashboardKeuanganAnggaranRoute: typeof DashboardKeuanganAnggaranRoute
  DashboardKinerjaDivisiRoute: typeof DashboardKinerjaDivisiRoute
  DashboardPengaduanLayananPublikRoute: typeof DashboardPengaduanLayananPublikRoute
  DashboardPengaturanRoute: typeof DashboardPengaturanRouteWithChildren
  DashboardSosialRoute: typeof DashboardSosialRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardBantuanRoute: DashboardBantuanRoute,
  DashboardBumdesRoute: DashboardBumdesRoute,
  DashboardDemografiPekerjaanRoute: DashboardDemografiPekerjaanRoute,
  DashboardJennaAnalyticRoute: DashboardJennaAnalyticRoute,
  DashboardKeamananRoute: DashboardKeamananRoute,
  DashboardKeuanganAnggaranRoute: DashboardKeuanganAnggaranRoute,
  DashboardKinerjaDivisiRoute: DashboardKinerjaDivisiRoute,
  DashboardPengaduanLayananPublikRoute: DashboardPengaduanLayananPublikRoute,
  DashboardPengaturanRoute: DashboardPengaturanRouteWithChildren,
  DashboardSosialRoute: DashboardSosialRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ProfileEditRoute: ProfileEditRoute,
  UsersIdRoute: UsersIdRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
