/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SosialRouteImport } from './routes/sosial'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as PengaduanLayananPublikRouteImport } from './routes/pengaduan-layanan-publik'
import { Route as KinerjaDivisiRouteImport } from './routes/kinerja-divisi'
import { Route as KeuanganAnggaranRouteImport } from './routes/keuangan-anggaran'
import { Route as KeamananRouteImport } from './routes/keamanan'
import { Route as JennaAnalyticRouteImport } from './routes/jenna-analytic'
import { Route as DemografiPekerjaanRouteImport } from './routes/demografi-pekerjaan'
import { Route as BumdesRouteImport } from './routes/bumdes'
import { Route as BantuanRouteImport } from './routes/bantuan'
import { Route as ProfileRouteRouteImport } from './routes/profile/route'
import { Route as PengaturanRouteRouteImport } from './routes/pengaturan/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UsersIdRouteImport } from './routes/users/$id'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as PengaturanUmumRouteImport } from './routes/pengaturan/umum'
import { Route as PengaturanSinkronisasiRouteImport } from './routes/pengaturan/sinkronisasi'
import { Route as PengaturanNotifikasiRouteImport } from './routes/pengaturan/notifikasi'
import { Route as PengaturanKeamananRouteImport } from './routes/pengaturan/keamanan'
import { Route as PengaturanAksesDanTimRouteImport } from './routes/pengaturan/akses-dan-tim'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminApikeyRouteImport } from './routes/admin/apikey'

const SosialRoute = SosialRouteImport.update({
  id: '/sosial',
  path: '/sosial',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaduanLayananPublikRoute = PengaduanLayananPublikRouteImport.update({
  id: '/pengaduan-layanan-publik',
  path: '/pengaduan-layanan-publik',
  getParentRoute: () => rootRouteImport,
} as any)
const KinerjaDivisiRoute = KinerjaDivisiRouteImport.update({
  id: '/kinerja-divisi',
  path: '/kinerja-divisi',
  getParentRoute: () => rootRouteImport,
} as any)
const KeuanganAnggaranRoute = KeuanganAnggaranRouteImport.update({
  id: '/keuangan-anggaran',
  path: '/keuangan-anggaran',
  getParentRoute: () => rootRouteImport,
} as any)
const KeamananRoute = KeamananRouteImport.update({
  id: '/keamanan',
  path: '/keamanan',
  getParentRoute: () => rootRouteImport,
} as any)
const JennaAnalyticRoute = JennaAnalyticRouteImport.update({
  id: '/jenna-analytic',
  path: '/jenna-analytic',
  getParentRoute: () => rootRouteImport,
} as any)
const DemografiPekerjaanRoute = DemografiPekerjaanRouteImport.update({
  id: '/demografi-pekerjaan',
  path: '/demografi-pekerjaan',
  getParentRoute: () => rootRouteImport,
} as any)
const BumdesRoute = BumdesRouteImport.update({
  id: '/bumdes',
  path: '/bumdes',
  getParentRoute: () => rootRouteImport,
} as any)
const BantuanRoute = BantuanRouteImport.update({
  id: '/bantuan',
  path: '/bantuan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanRouteRoute = PengaturanRouteRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const PengaturanUmumRoute = PengaturanUmumRouteImport.update({
  id: '/umum',
  path: '/umum',
  getParentRoute: () => PengaturanRouteRoute,
} as any)
const PengaturanSinkronisasiRoute = PengaturanSinkronisasiRouteImport.update({
  id: '/sinkronisasi',
  path: '/sinkronisasi',
  getParentRoute: () => PengaturanRouteRoute,
} as any)
const PengaturanNotifikasiRoute = PengaturanNotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => PengaturanRouteRoute,
} as any)
const PengaturanKeamananRoute = PengaturanKeamananRouteImport.update({
  id: '/keamanan',
  path: '/keamanan',
  getParentRoute: () => PengaturanRouteRoute,
} as any)
const PengaturanAksesDanTimRoute = PengaturanAksesDanTimRouteImport.update({
  id: '/akses-dan-tim',
  path: '/akses-dan-tim',
  getParentRoute: () => PengaturanRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApikeyRoute = AdminApikeyRouteImport.update({
  id: '/apikey',
  path: '/apikey',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/pengaturan': typeof PengaturanRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/bantuan': typeof BantuanRoute
  '/bumdes': typeof BumdesRoute
  '/demografi-pekerjaan': typeof DemografiPekerjaanRoute
  '/jenna-analytic': typeof JennaAnalyticRoute
  '/keamanan': typeof KeamananRoute
  '/keuangan-anggaran': typeof KeuanganAnggaranRoute
  '/kinerja-divisi': typeof KinerjaDivisiRoute
  '/pengaduan-layanan-publik': typeof PengaduanLayananPublikRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sosial': typeof SosialRoute
  '/admin/apikey': typeof AdminApikeyRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/pengaturan/akses-dan-tim': typeof PengaturanAksesDanTimRoute
  '/pengaturan/keamanan': typeof PengaturanKeamananRoute
  '/pengaturan/notifikasi': typeof PengaturanNotifikasiRoute
  '/pengaturan/sinkronisasi': typeof PengaturanSinkronisasiRoute
  '/pengaturan/umum': typeof PengaturanUmumRoute
  '/profile/edit': typeof ProfileEditRoute
  '/users/$id': typeof UsersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pengaturan': typeof PengaturanRouteRouteWithChildren
  '/bantuan': typeof BantuanRoute
  '/bumdes': typeof BumdesRoute
  '/demografi-pekerjaan': typeof DemografiPekerjaanRoute
  '/jenna-analytic': typeof JennaAnalyticRoute
  '/keamanan': typeof KeamananRoute
  '/keuangan-anggaran': typeof KeuanganAnggaranRoute
  '/kinerja-divisi': typeof KinerjaDivisiRoute
  '/pengaduan-layanan-publik': typeof PengaduanLayananPublikRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sosial': typeof SosialRoute
  '/admin/apikey': typeof AdminApikeyRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/pengaturan/akses-dan-tim': typeof PengaturanAksesDanTimRoute
  '/pengaturan/keamanan': typeof PengaturanKeamananRoute
  '/pengaturan/notifikasi': typeof PengaturanNotifikasiRoute
  '/pengaturan/sinkronisasi': typeof PengaturanSinkronisasiRoute
  '/pengaturan/umum': typeof PengaturanUmumRoute
  '/profile/edit': typeof ProfileEditRoute
  '/users/$id': typeof UsersIdRoute
  '/admin': typeof AdminIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/pengaturan': typeof PengaturanRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/bantuan': typeof BantuanRoute
  '/bumdes': typeof BumdesRoute
  '/demografi-pekerjaan': typeof DemografiPekerjaanRoute
  '/jenna-analytic': typeof JennaAnalyticRoute
  '/keamanan': typeof KeamananRoute
  '/keuangan-anggaran': typeof KeuanganAnggaranRoute
  '/kinerja-divisi': typeof KinerjaDivisiRoute
  '/pengaduan-layanan-publik': typeof PengaduanLayananPublikRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sosial': typeof SosialRoute
  '/admin/apikey': typeof AdminApikeyRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/pengaturan/akses-dan-tim': typeof PengaturanAksesDanTimRoute
  '/pengaturan/keamanan': typeof PengaturanKeamananRoute
  '/pengaturan/notifikasi': typeof PengaturanNotifikasiRoute
  '/pengaturan/sinkronisasi': typeof PengaturanSinkronisasiRoute
  '/pengaturan/umum': typeof PengaturanUmumRoute
  '/profile/edit': typeof ProfileEditRoute
  '/users/$id': typeof UsersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/pengaturan'
    | '/profile'
    | '/bantuan'
    | '/bumdes'
    | '/demografi-pekerjaan'
    | '/jenna-analytic'
    | '/keamanan'
    | '/keuangan-anggaran'
    | '/kinerja-divisi'
    | '/pengaduan-layanan-publik'
    | '/signin'
    | '/signup'
    | '/sosial'
    | '/admin/apikey'
    | '/admin/settings'
    | '/admin/users'
    | '/pengaturan/akses-dan-tim'
    | '/pengaturan/keamanan'
    | '/pengaturan/notifikasi'
    | '/pengaturan/sinkronisasi'
    | '/pengaturan/umum'
    | '/profile/edit'
    | '/users/$id'
    | '/admin/'
    | '/profile/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pengaturan'
    | '/bantuan'
    | '/bumdes'
    | '/demografi-pekerjaan'
    | '/jenna-analytic'
    | '/keamanan'
    | '/keuangan-anggaran'
    | '/kinerja-divisi'
    | '/pengaduan-layanan-publik'
    | '/signin'
    | '/signup'
    | '/sosial'
    | '/admin/apikey'
    | '/admin/settings'
    | '/admin/users'
    | '/pengaturan/akses-dan-tim'
    | '/pengaturan/keamanan'
    | '/pengaturan/notifikasi'
    | '/pengaturan/sinkronisasi'
    | '/pengaturan/umum'
    | '/profile/edit'
    | '/users/$id'
    | '/admin'
    | '/profile'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/pengaturan'
    | '/profile'
    | '/bantuan'
    | '/bumdes'
    | '/demografi-pekerjaan'
    | '/jenna-analytic'
    | '/keamanan'
    | '/keuangan-anggaran'
    | '/kinerja-divisi'
    | '/pengaduan-layanan-publik'
    | '/signin'
    | '/signup'
    | '/sosial'
    | '/admin/apikey'
    | '/admin/settings'
    | '/admin/users'
    | '/pengaturan/akses-dan-tim'
    | '/pengaturan/keamanan'
    | '/pengaturan/notifikasi'
    | '/pengaturan/sinkronisasi'
    | '/pengaturan/umum'
    | '/profile/edit'
    | '/users/$id'
    | '/admin/'
    | '/profile/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  PengaturanRouteRoute: typeof PengaturanRouteRouteWithChildren
  ProfileRouteRoute: typeof ProfileRouteRouteWithChildren
  BantuanRoute: typeof BantuanRoute
  BumdesRoute: typeof BumdesRoute
  DemografiPekerjaanRoute: typeof DemografiPekerjaanRoute
  JennaAnalyticRoute: typeof JennaAnalyticRoute
  KeamananRoute: typeof KeamananRoute
  KeuanganAnggaranRoute: typeof KeuanganAnggaranRoute
  KinerjaDivisiRoute: typeof KinerjaDivisiRoute
  PengaduanLayananPublikRoute: typeof PengaduanLayananPublikRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SosialRoute: typeof SosialRoute
  UsersIdRoute: typeof UsersIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sosial': {
      id: '/sosial'
      path: '/sosial'
      fullPath: '/sosial'
      preLoaderRoute: typeof SosialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaduan-layanan-publik': {
      id: '/pengaduan-layanan-publik'
      path: '/pengaduan-layanan-publik'
      fullPath: '/pengaduan-layanan-publik'
      preLoaderRoute: typeof PengaduanLayananPublikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kinerja-divisi': {
      id: '/kinerja-divisi'
      path: '/kinerja-divisi'
      fullPath: '/kinerja-divisi'
      preLoaderRoute: typeof KinerjaDivisiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keuangan-anggaran': {
      id: '/keuangan-anggaran'
      path: '/keuangan-anggaran'
      fullPath: '/keuangan-anggaran'
      preLoaderRoute: typeof KeuanganAnggaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keamanan': {
      id: '/keamanan'
      path: '/keamanan'
      fullPath: '/keamanan'
      preLoaderRoute: typeof KeamananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jenna-analytic': {
      id: '/jenna-analytic'
      path: '/jenna-analytic'
      fullPath: '/jenna-analytic'
      preLoaderRoute: typeof JennaAnalyticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demografi-pekerjaan': {
      id: '/demografi-pekerjaan'
      path: '/demografi-pekerjaan'
      fullPath: '/demografi-pekerjaan'
      preLoaderRoute: typeof DemografiPekerjaanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bumdes': {
      id: '/bumdes'
      path: '/bumdes'
      fullPath: '/bumdes'
      preLoaderRoute: typeof BumdesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bantuan': {
      id: '/bantuan'
      path: '/bantuan'
      fullPath: '/bantuan'
      preLoaderRoute: typeof BantuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/pengaturan/umum': {
      id: '/pengaturan/umum'
      path: '/umum'
      fullPath: '/pengaturan/umum'
      preLoaderRoute: typeof PengaturanUmumRouteImport
      parentRoute: typeof PengaturanRouteRoute
    }
    '/pengaturan/sinkronisasi': {
      id: '/pengaturan/sinkronisasi'
      path: '/sinkronisasi'
      fullPath: '/pengaturan/sinkronisasi'
      preLoaderRoute: typeof PengaturanSinkronisasiRouteImport
      parentRoute: typeof PengaturanRouteRoute
    }
    '/pengaturan/notifikasi': {
      id: '/pengaturan/notifikasi'
      path: '/notifikasi'
      fullPath: '/pengaturan/notifikasi'
      preLoaderRoute: typeof PengaturanNotifikasiRouteImport
      parentRoute: typeof PengaturanRouteRoute
    }
    '/pengaturan/keamanan': {
      id: '/pengaturan/keamanan'
      path: '/keamanan'
      fullPath: '/pengaturan/keamanan'
      preLoaderRoute: typeof PengaturanKeamananRouteImport
      parentRoute: typeof PengaturanRouteRoute
    }
    '/pengaturan/akses-dan-tim': {
      id: '/pengaturan/akses-dan-tim'
      path: '/akses-dan-tim'
      fullPath: '/pengaturan/akses-dan-tim'
      preLoaderRoute: typeof PengaturanAksesDanTimRouteImport
      parentRoute: typeof PengaturanRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/apikey': {
      id: '/admin/apikey'
      path: '/apikey'
      fullPath: '/admin/apikey'
      preLoaderRoute: typeof AdminApikeyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminApikeyRoute: typeof AdminApikeyRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminApikeyRoute: AdminApikeyRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PengaturanRouteRouteChildren {
  PengaturanAksesDanTimRoute: typeof PengaturanAksesDanTimRoute
  PengaturanKeamananRoute: typeof PengaturanKeamananRoute
  PengaturanNotifikasiRoute: typeof PengaturanNotifikasiRoute
  PengaturanSinkronisasiRoute: typeof PengaturanSinkronisasiRoute
  PengaturanUmumRoute: typeof PengaturanUmumRoute
}

const PengaturanRouteRouteChildren: PengaturanRouteRouteChildren = {
  PengaturanAksesDanTimRoute: PengaturanAksesDanTimRoute,
  PengaturanKeamananRoute: PengaturanKeamananRoute,
  PengaturanNotifikasiRoute: PengaturanNotifikasiRoute,
  PengaturanSinkronisasiRoute: PengaturanSinkronisasiRoute,
  PengaturanUmumRoute: PengaturanUmumRoute,
}

const PengaturanRouteRouteWithChildren = PengaturanRouteRoute._addFileChildren(
  PengaturanRouteRouteChildren,
)

interface ProfileRouteRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteRouteChildren: ProfileRouteRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteRouteWithChildren = ProfileRouteRoute._addFileChildren(
  ProfileRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  PengaturanRouteRoute: PengaturanRouteRouteWithChildren,
  ProfileRouteRoute: ProfileRouteRouteWithChildren,
  BantuanRoute: BantuanRoute,
  BumdesRoute: BumdesRoute,
  DemografiPekerjaanRoute: DemografiPekerjaanRoute,
  JennaAnalyticRoute: JennaAnalyticRoute,
  KeamananRoute: KeamananRoute,
  KeuanganAnggaranRoute: KeuanganAnggaranRoute,
  KinerjaDivisiRoute: KinerjaDivisiRoute,
  PengaduanLayananPublikRoute: PengaduanLayananPublikRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SosialRoute: SosialRoute,
  UsersIdRoute: UsersIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
